### ISSUE TITLE
EllipticalMirrorParam(OE) parameters setting

### ISSUE THREAD

**Issue by wholingfei** [kklmn/xrt#29]
Hi, 
I want to make sure if we deal with the EllipticalMirrorParam(OE) properly. 
We've found that if the main optical axis has a deflection angle, e.g.beam reflected from one single crystal, the next EllipticalMirrorParm's pitch angle should not be set as the same as the plane mirror or toroidal mirror. Instead, pitch angle of EllipticalMirrorParm was set to be the "desired" pitch to the deflected main optical axis. In addiation, we have to set extraPitch to rotate the mirror local coordinate system to be parallel to the deflected main optical axis.
We guess that it may be related to the fact that pitch parameter in EllipticalMirrorParam(OE) play an important role in other auxiliary parameters calculation. 
May I ask is there anything wrong with our approach?

**Comment by kklmn** [comment]
Yes, you're right. If the optical axis is deflected, the parametric representation needs a shifted pitch angle. In the present implementation this is not available. I will implement it in about a week.
Thank you for discovering the problem!

**Comment by kklmn** [comment]
Hi,
Please try the last update. Please look at the [docs](https://xrt.readthedocs.io/raycing.html#xrt.backends.raycing.oes.EllipticalMirrorParam) and a new test script `test_param_mirror.py` for a usage example and get back with your results/comments.

**Comment by kklmn** [comment]
Yes, you're right. Thanks for finding it!
I've fixed it. Please try the update.

**Comment by wholingfei** [comment]
Hi, the test script `test_param_mirror.py` could run correctly in my computer now.
However, I still can't successfully apply the new EllipticalMirrorParam to my own codes. Here is the main building of the optical elements .
```Python
    beamLine.TorM = roe.ToroidMirror(beamLine, 'ToroidMirrir', [0., 41000., 0.], 
                                     pitch=2.5e-3, 
                                     roll=-np.pi/2, 
                                     material=None, 
                                     limPhysX=[-20., 20.], limPhysY=[-256., 256.], 
                                     R=[41000., 19000.], r=[41000., 19000.])
    beamLine.Screen2 = rsc.Screen(beamLine, '2ndSource', [0., 60000., 0.])
    beamLine.Screen2.center[0] = beamLine.TorM.center[0] - (beamLine.Screen2.center[1] - 
                                    beamLine.TorM.center[1])*np.tan(2*beamLine.TorM.pitch)
    KB1_center1 = 76440.
    KB1_center0 = beamLine.TorM.center[0] - (KB1_center1- 
                                      beamLine.TorM.center[1])*np.tan(2*beamLine.TorM.pitch)
    beamLine.KB1 = roe.EllipticalMirrorParam(beamLine, 'VKB', [0., 76440, 0.], 
                                             pitch=1.5e-3, material=mPt, 
                                             limPhysY=[-190., 190.], 
                                             p=16440., q=1560., 
                                             isCylindrical=True)

    f1_x = beamLine.TorM.center[0] - (beamLine.Screen2.center[1] - 
                          beamLine.TorM.center[1])*np.tan(2*beamLine.TorM.pitch)
    KB2_center1 = 76870.
    KB2_center0 = beamLine.Screen2.center[0] - (KB2_center1-beamLine.Screen2.center[1]) * 
                                                  np.tan(2*beamLine.TorM.pitch)
    KB2_center2 = beamLine.KB1.center[2] + (KB2_center1-KB1_center1)
                             *np.tan(2*beamLine.KB1.pitch)
    
    #beamLine.KB2 = roe.EllipticalMirrorParam(beamLine, 'HKB', 
    #                                 [KB2_center0, 76870, KB2_center2], 
    #                                 pitch=1.5e-3, material=mPt,  
    #                                 roll=np.pi/2, extraPitch=-5.0e-3, 
    #                                 limPhysY=[-195., 195.], 
    #                                 p=16870., q=1130., isCylindrical=True)
    beamLine.KB2 = roe.EllipticalMirrorParam(beamLine, 'HKB', 
                                   [KB2_center0, 76870, KB2_center2], 
                                   pitch=1.5e-3-5.e-3, material=mPt, 
                                   roll=np.pi/2,
                                   limPhysY=[-195., 195.], 
                                   f1=[f1_x, 60000., 0.], q=1130., 
                                   isCylindrical=True)
    beamLine.KBSampleShort = rsc.Screen(beamLine, 'AtSamplePos', [0., 78000., 0])
```
The commented out statements are my original treatment. Toroidal mirror provide a second source at Screen2. 
I think the main difference between my codes and the test script is that my codes deflect in sagittal plane not the meridian as shown in test script. 

I just want to make sure whether it's my own problem in parameter setting or not.
Thanks for your quick update anyway!

**Comment by kklmn** [comment]
Hi,
I have now implemented the most general case and have tested it with `test_param_mirror.py`. I have removed pitch from the ellipse calculations and put the general coordinate system transformation. Please try the last update.
Note also that when you use a horizontally deflecting mirror and the incoming beam is not horizontal, you should also define a yaw angle. Specify a sequence for the rotations to get the orientation that you expect. Please look at `test_param_mirror.py` for yaw.
